// Generated by https://quicktype.io

import type { Meta, MpaRating, Stat, Torrent } from "./utils";

export interface MovieResponse {
  status: Stat;
  status_message: string;
  data: Data;
  "@meta": Meta;
}

export interface Data {
  movie_count: number;
  limit: number;
  page_number: number;
  movies: Movie[];
}

export interface Movie {
  id: number;
  url: string;
  imdb_code: string;
  title: string;
  title_english: string;
  title_long: string;
  slug: string;
  year: number;
  rating: number;
  runtime: number;
  genres: string[];
  summary: string;
  description_full: string;
  synopsis: string;
  yt_trailer_code: string;
  language: string;
  mpa_rating: MpaRating;
  background_image: string;
  background_image_original: string;
  small_cover_image: string;
  medium_cover_image: string;
  large_cover_image: string;
  state: Stat;
  torrents: Torrent[];
  date_uploaded: string;
  date_uploaded_unix: number;
}
